import { Ticket, User } from '@/types'

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'ישראל ישראלי', email: 'admin@example.com', role: 'super_admin' },
  { id: 'u2', name: 'רחל כהן', email: 'qc@example.com', role: 'quality_control' },
  { id: 'u3', name: 'משה לוי', email: 'pm.tmt@example.com', role: 'contractor_pm', contractor: 'TMT' },
  { id: 'u4', name: 'דוד ברוך', email: 'emp.tmt@example.com', role: 'contractor_employee', contractor: 'TMT' },
  { id: 'u5', name: 'יוסף אברהם', email: 'pm.ebs@example.com', role: 'contractor_pm', contractor: 'EBS' },
  { id: 'u6', name: 'שרה מזרחי', email: 'emp.ebs@example.com', role: 'contractor_employee', contractor: 'EBS' },
]

const d = (offsetDays: number) => new Date(Date.now() + offsetDays * 86400000).toISOString()
const date = (offsetDays: number) => new Date(Date.now() + offsetDays * 86400000).toISOString().split('T')[0]

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 't1',
    ticketNumber: 'TP-01-001-P-001-001',
    contractor: 'TMT',
    assignedToId: 'u3',
    assignedToName: 'משה לוי',
    status: 'פתוח',
    priority: 'גבוהה',
    description: 'ממשק חשמלי לא תקין בלוח מספר 3 – נמצאה חריגה בערכי המתח בהפרש של 15% מהנדרש',
    testPhase: 'לפני טסט',
    targetDate: date(1),
    testDate: date(1),
    notes: '',
    createdAt: d(-7),
    updatedAt: d(-7),
    openedAt: d(-7),
    createdByName: 'רחל כהן',
    createdById: 'u2',
    chatMessages: [
      {
        id: 'c1',
        ticketId: 't1',
        userId: 'u2',
        userName: 'רחל כהן',
        userRole: 'quality_control',
        message: 'נמצאה תקלה חמורה בלוח 3. נדרש טיפול דחוף לפני הטסט המתוכנן.',
        createdAt: d(-7),
      },
    ],
    statusHistory: [
      { id: 'sh1', ticketId: 't1', userId: 'u2', userName: 'רחל כהן', oldStatus: 'פתוח', newStatus: 'פתוח', createdAt: d(-7) },
    ],
  },
  {
    id: 't2',
    ticketNumber: 'TP-01-002-P-001-002',
    contractor: 'EBS',
    assignedToId: 'u5',
    assignedToName: 'יוסף אברהם',
    status: 'בטיפול',
    priority: 'בינונית',
    description: 'כבלי חיווט לא מסומנים בהתאם לתקן – מעל 20 כבלים ללא תווית בחדר שנאים',
    testPhase: 'אחרי טסט',
    targetDate: date(7),
    testDate: date(7),
    notes: 'מזמינים תוויות חדשות, יגיעו מחר. נטפל בהקדם.',
    createdAt: d(-3),
    updatedAt: d(-1),
    openedAt: d(-3),
    createdByName: 'רחל כהן',
    createdById: 'u2',
    chatMessages: [
      {
        id: 'c2',
        ticketId: 't2',
        userId: 'u2',
        userName: 'רחל כהן',
        userRole: 'quality_control',
        message: 'יש לתקן את סימון הכבלים לפי תקן IEC 60445 תוך 48 שעות.',
        createdAt: d(-3),
      },
      {
        id: 'c3',
        ticketId: 't2',
        userId: 'u5',
        userName: 'יוסף אברהם',
        userRole: 'contractor_pm',
        message: 'קיבלנו את ההערה. הוזמנו תוויות, יגיעו מחר. נסיים את הסימון תוך יומיים.',
        createdAt: d(-1),
      },
    ],
    statusHistory: [
      { id: 'sh2', ticketId: 't2', userId: 'u2', userName: 'רחל כהן', oldStatus: 'פתוח', newStatus: 'פתוח', createdAt: d(-3) },
      { id: 'sh3', ticketId: 't2', userId: 'u5', userName: 'יוסף אברהם', oldStatus: 'פתוח', newStatus: 'בטיפול', createdAt: d(-1) },
    ],
  },
  {
    id: 't3',
    ticketNumber: 'TP-02-001-P-002-001',
    contractor: 'TMT',
    assignedToId: 'u4',
    assignedToName: 'דוד ברוך',
    status: 'ממתין לאישור',
    priority: 'נמוכה',
    description: 'חוסר בתיעוד טכני – אין תכניות As-Built לאזור B',
    testDate: date(-1),
    targetDate: date(-1),
    notes: 'שלחנו את התכניות המעודכנות למייל בקרת האיכות. ממתינים לאישור.',
    createdAt: d(-10),
    updatedAt: d(-1),
    openedAt: d(-10),
    createdByName: 'ישראל ישראלי',
    createdById: 'u1',
    chatMessages: [
      {
        id: 'c4',
        ticketId: 't3',
        userId: 'u1',
        userName: 'ישראל ישראלי',
        userRole: 'super_admin',
        message: 'חסרות תכניות As-Built לאזור B. יש להמציא תוך שבוע.',
        createdAt: d(-10),
      },
      {
        id: 'c5',
        ticketId: 't3',
        userId: 'u3',
        userName: 'משה לוי',
        userRole: 'contractor_pm',
        message: 'שלחנו את התכניות המלאות למייל. נא לאשר.',
        createdAt: d(-1),
      },
    ],
    statusHistory: [
      { id: 'sh4', ticketId: 't3', userId: 'u1', userName: 'ישראל ישראלי', oldStatus: 'פתוח', newStatus: 'פתוח', createdAt: d(-10) },
      { id: 'sh5', ticketId: 't3', userId: 'u4', userName: 'דוד ברוך', oldStatus: 'פתוח', newStatus: 'בטיפול', createdAt: d(-3) },
      { id: 'sh6', ticketId: 't3', userId: 'u4', userName: 'דוד ברוך', oldStatus: 'בטיפול', newStatus: 'ממתין לאישור', createdAt: d(-1) },
    ],
  },
  {
    id: 't4',
    ticketNumber: 'TP-02-003-P-003-001',
    contractor: 'EBS',
    status: 'סגור',
    priority: 'גבוהה',
    description: 'קצר חשמלי בלוח בקרה ראשי – מערכת אינה מגיבה',
    createdAt: d(-14),
    updatedAt: d(-7),
    openedAt: d(-14),
    closedAt: d(-7),
    createdByName: 'רחל כהן',
    createdById: 'u2',
    chatMessages: [],
    statusHistory: [
      { id: 'sh7', ticketId: 't4', userId: 'u2', userName: 'רחל כהן', oldStatus: 'פתוח', newStatus: 'פתוח', createdAt: d(-14) },
      { id: 'sh8', ticketId: 't4', userId: 'u2', userName: 'רחל כהן', oldStatus: 'בטיפול', newStatus: 'סגור', createdAt: d(-7) },
    ],
  },
  {
    id: 't5',
    ticketNumber: 'TP-03-001-P-001-003',
    contractor: 'TMT',
    assignedToId: 'u3',
    assignedToName: 'משה לוי',
    status: 'פתוח',
    priority: 'בינונית',
    description: 'ציוד הגנה לא מותקן בתחנת הכוח – חסרים מגינים על מחברים חשופים',
    testPhase: 'לפני טסט',
    targetDate: date(2),
    testDate: date(2),
    notes: '',
    createdAt: d(-2),
    updatedAt: d(-2),
    openedAt: d(-2),
    createdByName: 'רחל כהן',
    createdById: 'u2',
    chatMessages: [],
    statusHistory: [
      { id: 'sh9', ticketId: 't5', userId: 'u2', userName: 'רחל כהן', oldStatus: 'פתוח', newStatus: 'פתוח', createdAt: d(-2) },
    ],
  },
]
